use anyhow::Result;
use directories::ProjectDirs;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppConfig {
    pub username: String,
    pub password: String,
    pub auto_download: bool,
    pub last_server: Option<String>,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            username: String::new(),
            password: String::new(),
            auto_download: true,
            last_server: None,
        }
    }
}

pub struct ConfigManager {
    config_path: PathBuf,
    wg_config_dir: PathBuf,
}

impl ConfigManager {
    pub fn new() -> Result<Self> {
        let proj_dirs = ProjectDirs::from("org", "wireguard", "wireguard-tui")
            .ok_or_else(|| anyhow::anyhow!("Failed to get project directories"))?;

        let config_dir = proj_dirs.config_dir();
        let config_path = config_dir.join("config.toml");
        let wg_config_dir = PathBuf::from("/etc/wireguard");

        fs::create_dir_all(config_dir)?;

        let manager = Self {
            config_path,
            wg_config_dir,
        };

        // Auto-generate config template if not exists
        manager.ensure_config_exists()?;

        Ok(manager)
    }

    fn ensure_config_exists(&self) -> Result<()> {
        if !self.config_path.exists() {
            self.create_config_template()?;
        }
        Ok(())
    }

    fn create_config_template(&self) -> Result<()> {
        let template = r#"# WireGuard TUI Configuration File
#
# This file is automatically generated on first run.
# Please update with your StrongVPN credentials.
#
# Get your credentials from:
# 1. Login to https://strongtech.org/account/
# 2. Click "Account Setup Instructions"
# 3. Look for "VPN Account Information"
# 4. Username starts with 'a'
#
# Note: These are your VPN credentials (AIO Username/Password),
# NOT your website login email/password!

# Your StrongVPN username (starts with 'a')
username = "a314393"

# Your StrongVPN password
password = "L7W8cXG3MH"

# Automatically download configs on first run
auto_download = true

# Last connected server (managed automatically)
# last_server = "server-name"
"#;

        fs::write(&self.config_path, template)?;
        Ok(())
    }

    pub fn load_config(&self) -> Result<AppConfig> {
        if !self.config_path.exists() {
            self.create_config_template()?;
        }

        let content = fs::read_to_string(&self.config_path)?;
        let config = toml::from_str(&content)?;
        Ok(config)
    }

    pub fn get_config_path_str(&self) -> String {
        self.config_path.display().to_string()
    }

    pub fn get_wg_config_dir(&self) -> &Path {
        &self.wg_config_dir
    }

    pub fn list_configs(&self) -> Result<Vec<String>> {
        let mut configs = Vec::new();

        // 检查目录是否存在且可读
        if !self.wg_config_dir.exists() {
            return Ok(configs);
        }

        // 尝试读取目录，如果权限不足则返回空列表而不是错误
        match fs::read_dir(&self.wg_config_dir) {
            Ok(entries) => {
                for entry in entries {
                    if let Ok(entry) = entry {
                        let path = entry.path();
                        if path.extension().map_or(false, |ext| ext == "conf") {
                            if let Some(name) = path.file_stem() {
                                if let Some(name_str) = name.to_str() {
                                    configs.push(name_str.to_string());
                                }
                            }
                        }
                    }
                }
            }
            Err(_) => {
                // 权限不足，返回空列表
            }
        }

        configs.sort();
        Ok(configs)
    }

    pub fn get_config_path(&self, name: &str) -> PathBuf {
        self.wg_config_dir.join(format!("{}.conf", name))
    }
}
