use crate::commands::CommandExecutor;
use anyhow::{anyhow, bail, Context, Result};
use directories::ProjectDirs;
use serde::{Deserialize, Serialize};
use std::fs::{self, OpenOptions};
use std::io::{ErrorKind, Write};
use std::path::{Path, PathBuf};

#[cfg(unix)]
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

const CONFIG_TEMPLATE: &str = r#"# WireGuard TUI Configuration File
#
# This file is automatically generated on first run.
# Provider credentials are intentionally never stored or handled by this app.
# Sign in only inside your browser, then import downloaded configs explicitly.
"#;

/// Linux interface names are limited to IFNAMSIZ - 1 bytes. `wg-quick`
/// further restricts names to this ASCII character set.
pub fn validate_interface_name(name: &str) -> Result<()> {
    if name.is_empty() || name.len() > 15 {
        bail!("WireGuard interface name must contain 1 to 15 ASCII characters");
    }

    if name.starts_with('-') {
        bail!("WireGuard interface names must not begin with '-'");
    }

    if name == "." || name == ".." || matches!(name, "all" | "interfaces") {
        bail!("Reserved WireGuard interface name: {name}");
    }

    if !name.bytes().all(|byte| {
        byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'=' | b'+' | b'.' | b'-')
    }) {
        bail!(
            "WireGuard interface names may only contain ASCII letters, digits, '_', '=', '+', '.', and '-'"
        );
    }

    Ok(())
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ConfigDetails {
    pub interface_address: Option<String>,
    pub dns: Option<String>,
    pub peer_public_key: Option<String>,
    pub endpoint: Option<String>,
    pub allowed_ips: Option<String>,
    pub persistent_keepalive: Option<String>,
    pub private_key_configured: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ConfigSection {
    Interface,
    Peer,
    Other,
}

fn section_from_line(line: &str) -> Option<ConfigSection> {
    if !(line.starts_with('[') && line.ends_with(']')) {
        return None;
    }

    Some(
        match line[1..line.len() - 1].trim().to_ascii_lowercase().as_str() {
            "interface" => ConfigSection::Interface,
            "peer" => ConfigSection::Peer,
            _ => ConfigSection::Other,
        },
    )
}

fn is_command_hook(key: &str) -> bool {
    matches!(key, "preup" | "postup" | "predown" | "postdown")
}

impl ConfigDetails {
    pub fn from_wireguard_config(content: &str) -> Self {
        let mut details = Self::default();
        let mut section = None;
        let mut peer_sections = 0usize;

        for raw_line in content.lines() {
            let line = raw_line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            if let Some(next_section) = section_from_line(line) {
                if next_section == ConfigSection::Peer {
                    peer_sections += 1;
                }
                section = Some(next_section);
                continue;
            }

            let Some((key, value)) = line.split_once('=') else {
                continue;
            };

            let key = key.trim().to_ascii_lowercase();
            let value = value.trim();
            match (section, key.as_str()) {
                (Some(ConfigSection::Interface), "address")
                    if details.interface_address.is_none() =>
                {
                    details.interface_address = Some(value.to_string());
                }
                (Some(ConfigSection::Interface), "dns") if details.dns.is_none() => {
                    details.dns = Some(value.to_string());
                }
                (Some(ConfigSection::Interface), "privatekey") => {
                    details.private_key_configured |= !value.is_empty();
                }
                (Some(ConfigSection::Peer), "publickey")
                    if peer_sections == 1 && details.peer_public_key.is_none() =>
                {
                    details.peer_public_key = Some(value.to_string());
                }
                (Some(ConfigSection::Peer), "endpoint")
                    if peer_sections == 1 && details.endpoint.is_none() =>
                {
                    details.endpoint = Some(value.to_string());
                }
                (Some(ConfigSection::Peer), "allowedips")
                    if peer_sections == 1 && details.allowed_ips.is_none() =>
                {
                    details.allowed_ips = Some(value.to_string());
                }
                (Some(ConfigSection::Peer), "persistentkeepalive")
                    if peer_sections == 1 && details.persistent_keepalive.is_none() =>
                {
                    details.persistent_keepalive = Some(value.to_string());
                }
                _ => {}
            }
        }

        details
    }
}

/// Validate the security-sensitive minimum structure of a WireGuard client
/// configuration. Command hooks are deliberately rejected because `wg-quick`
/// executes them with the privileges used to bring the interface up.
pub fn validate_wireguard_client_config(content: &str) -> Result<ConfigDetails> {
    if content.is_empty() {
        bail!("WireGuard configuration is empty");
    }

    if content
        .chars()
        .any(|character| character.is_control() && !matches!(character, '\n' | '\r' | '\t'))
    {
        bail!("WireGuard configuration contains control characters");
    }

    let mut section = None;
    let mut interface_sections = 0usize;
    let mut peer_sections = 0usize;
    let mut interface_private_key = false;
    let mut peer_public_keys: Vec<bool> = Vec::new();

    for (line_index, raw_line) in content.lines().enumerate() {
        let line_number = line_index + 1;
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some(next_section) = section_from_line(line) {
            match next_section {
                ConfigSection::Interface => {
                    interface_sections += 1;
                    if interface_sections > 1 {
                        bail!("Multiple [Interface] sections are not supported");
                    }
                }
                ConfigSection::Peer => {
                    peer_sections += 1;
                    peer_public_keys.push(false);
                }
                ConfigSection::Other => {
                    bail!("Unsupported configuration section on line {line_number}");
                }
            }
            section = Some(next_section);
            continue;
        }

        let (key, value) = line
            .split_once('=')
            .ok_or_else(|| anyhow!("Malformed configuration line {line_number}"))?;
        let key = key.trim().to_ascii_lowercase();
        let value = value.trim();

        if is_command_hook(&key) {
            bail!("wg-quick command hook '{key}' is not allowed");
        }

        match section {
            Some(ConfigSection::Interface) => {
                if key == "privatekey" && !value.is_empty() {
                    interface_private_key = true;
                }
            }
            Some(ConfigSection::Peer) => {
                if key == "publickey" && !value.is_empty() {
                    if let Some(public_key) = peer_public_keys.last_mut() {
                        *public_key = true;
                    }
                }
            }
            Some(ConfigSection::Other) => unreachable!("other sections are rejected above"),
            None => bail!("Configuration value outside a section on line {line_number}"),
        }
    }

    if interface_sections != 1 {
        bail!("WireGuard configuration must contain exactly one [Interface] section");
    }
    if !interface_private_key {
        bail!("[Interface] must contain a non-empty PrivateKey");
    }
    if peer_sections == 0 {
        bail!("WireGuard client configuration must contain at least one [Peer] section");
    }
    if let Some(missing_index) = peer_public_keys.iter().position(|configured| !configured) {
        bail!(
            "[Peer] {} must contain a non-empty PublicKey",
            missing_index + 1
        );
    }

    Ok(ConfigDetails::from_wireguard_config(content))
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(default)]
pub struct AppConfig {}

#[derive(Debug, Clone)]
pub struct ConfigManager {
    config_path: PathBuf,
    wg_config_dir: PathBuf,
}

impl ConfigManager {
    pub fn new() -> Result<Self> {
        let proj_dirs = ProjectDirs::from("org", "wireguard", "wireguard-tui")
            .ok_or_else(|| anyhow!("Failed to get project directories"))?;

        Self::with_directories(proj_dirs.config_dir(), Path::new("/etc/wireguard"))
    }

    /// Construct a manager with explicit directories. This avoids global HOME
    /// state in tests and lets embedders select a different WireGuard directory.
    pub fn with_directories(
        config_dir: impl AsRef<Path>,
        wg_config_dir: impl AsRef<Path>,
    ) -> Result<Self> {
        let config_dir = config_dir.as_ref();
        create_private_directory(config_dir)?;

        let manager = Self {
            config_path: config_dir.join("config.toml"),
            wg_config_dir: wg_config_dir.as_ref().to_path_buf(),
        };
        manager.ensure_config_exists()?;
        Ok(manager)
    }

    fn ensure_config_exists(&self) -> Result<()> {
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        options.mode(0o600);

        match options.open(&self.config_path) {
            Ok(mut file) => {
                if let Err(error) = (|| -> std::io::Result<()> {
                    file.write_all(CONFIG_TEMPLATE.as_bytes())?;
                    file.sync_all()?;
                    set_private_file_permissions(&self.config_path)?;
                    Ok(())
                })() {
                    let _ = fs::remove_file(&self.config_path);
                    return Err(error).context("Failed to create application config");
                }
            }
            Err(error) if error.kind() == ErrorKind::AlreadyExists => {
                let metadata = fs::symlink_metadata(&self.config_path)
                    .context("Failed to inspect application config")?;
                if !metadata.file_type().is_file() {
                    bail!("Application config path is not a regular file");
                }
                set_private_file_permissions(&self.config_path)?;
            }
            Err(error) => return Err(error).context("Failed to create application config"),
        }

        Ok(())
    }

    pub fn load_config(&self) -> Result<AppConfig> {
        self.ensure_config_exists()?;
        let content = fs::read_to_string(&self.config_path)?;
        let fields: toml::Table = toml::from_str(&content).map_err(|error: toml::de::Error| {
            let location = error
                .span()
                .map(|span| format!(" near byte {}", span.start))
                .unwrap_or_default();
            anyhow!(
                "Failed to parse application config{location}: {}",
                error.message()
            )
        })?;

        if !fields.is_empty() {
            self.remove_obsolete_fields()?;
        }

        Ok(AppConfig::default())
    }

    fn remove_obsolete_fields(&self) -> Result<()> {
        let mut options = OpenOptions::new();
        options.write(true).truncate(true);
        #[cfg(unix)]
        options.custom_flags(libc::O_NOFOLLOW);

        let mut file = options
            .open(&self.config_path)
            .context("Failed to migrate obsolete application config fields")?;
        file.write_all(CONFIG_TEMPLATE.as_bytes())
            .context("Failed to remove obsolete application config fields")?;
        file.sync_all()
            .context("Failed to persist migrated application config")?;
        set_private_file_permissions(&self.config_path)?;
        Ok(())
    }

    pub fn get_wg_config_dir(&self) -> &Path {
        &self.wg_config_dir
    }

    pub fn list_configs(&self) -> Result<Vec<String>> {
        if !self.wg_config_dir.exists() {
            return Ok(Vec::new());
        }

        let mut configs: Vec<String> = match fs::read_dir(&self.wg_config_dir) {
            Ok(entries) => entries
                .map(|entry| -> Result<Option<String>> {
                    let entry = entry?;
                    if !entry.file_type()?.is_file() {
                        return Ok(None);
                    }
                    let path = entry.path();
                    if path.extension().and_then(|extension| extension.to_str()) != Some("conf") {
                        return Ok(None);
                    }
                    let Some(name) = path.file_stem().and_then(|name| name.to_str()) else {
                        return Ok(None);
                    };
                    Ok(validate_interface_name(name)
                        .is_ok()
                        .then(|| name.to_string()))
                })
                .collect::<Result<Vec<_>>>()?
                .into_iter()
                .flatten()
                .collect(),
            Err(error) if error.kind() == ErrorKind::PermissionDenied => {
                CommandExecutor::list_config_names(&self.wg_config_dir)?
                    .into_iter()
                    .filter(|name| validate_interface_name(name).is_ok())
                    .collect()
            }
            Err(error) => {
                return Err(error).with_context(|| {
                    format!(
                        "Failed to list WireGuard configs in {}",
                        self.wg_config_dir.display()
                    )
                });
            }
        };

        configs.sort_by_key(|name| name.to_ascii_lowercase());
        configs.dedup();
        Ok(configs)
    }

    pub fn get_config_path(&self, name: &str) -> PathBuf {
        self.wg_config_dir.join(format!("{name}.conf"))
    }

    pub fn checked_config_path(&self, name: &str) -> Result<PathBuf> {
        validate_interface_name(name)?;
        Ok(self.get_config_path(name))
    }

    pub fn load_config_details(&self, name: &str) -> Result<ConfigDetails> {
        let path = self.checked_config_path(name)?;
        CommandExecutor::ensure_secure_config_path(&path)
            .with_context(|| format!("Unsafe installed config {}", path.display()))?;
        let content = self.read_config_for_inspection(name)?;
        Ok(ConfigDetails::from_wireguard_config(&content))
    }

    /// Revalidate an installed configuration immediately before any `wg-quick`
    /// operation. The inspected representation has private and preshared keys
    /// redacted; structural validation only needs to know that they are set.
    pub fn validate_config(&self, name: &str) -> Result<ConfigDetails> {
        let path = self.checked_config_path(name)?;
        CommandExecutor::ensure_secure_config_path(&path)
            .with_context(|| format!("Unsafe installed config {}", path.display()))?;
        let content = self.read_config_for_inspection(name)?;
        validate_wireguard_client_config(&content)
    }

    fn read_config_for_inspection(&self, name: &str) -> Result<String> {
        let path = self.checked_config_path(name)?;
        match fs::read_to_string(&path) {
            Ok(content) => Ok(redact_wireguard_secrets(&content)),
            Err(error) if error.kind() == ErrorKind::PermissionDenied => {
                // The privileged reader performs the same redaction before its
                // stdout crosses back into this unprivileged process.
                CommandExecutor::read_file(&path)
            }
            Err(error) => Err(error).with_context(|| format!("Failed to read {}", path.display())),
        }
    }
}

fn redact_wireguard_secrets(content: &str) -> String {
    let mut redacted = String::with_capacity(content.len());
    for line in content.lines() {
        let replacement = line.split_once('=').and_then(|(key, _)| {
            matches!(
                key.trim().to_ascii_lowercase().as_str(),
                "privatekey" | "presharedkey"
            )
            .then(|| format!("{key}= [redacted]"))
        });
        redacted.push_str(replacement.as_deref().unwrap_or(line));
        redacted.push('\n');
    }
    redacted
}

fn create_private_directory(path: &Path) -> Result<()> {
    fs::create_dir_all(path)?;
    let metadata = fs::symlink_metadata(path)?;
    if !metadata.file_type().is_dir() {
        bail!("Application config directory is not a regular directory");
    }
    #[cfg(unix)]
    fs::set_permissions(path, fs::Permissions::from_mode(0o700))?;
    Ok(())
}

fn set_private_file_permissions(path: &Path) -> std::io::Result<()> {
    #[cfg(unix)]
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{
        redact_wireguard_secrets, validate_interface_name, validate_wireguard_client_config,
        AppConfig, ConfigDetails, ConfigManager, CONFIG_TEMPLATE,
    };
    use std::fs;
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicU64, Ordering};

    #[cfg(unix)]
    use std::os::unix::fs::PermissionsExt;

    static TEMP_SEQUENCE: AtomicU64 = AtomicU64::new(0);

    struct TestDirectory(PathBuf);

    impl TestDirectory {
        fn new(label: &str) -> Self {
            let sequence = TEMP_SEQUENCE.fetch_add(1, Ordering::Relaxed);
            let path = std::env::temp_dir().join(format!(
                "wireguard-tui-config-{label}-{}-{sequence}",
                std::process::id()
            ));
            fs::create_dir(&path).expect("create test directory");
            Self(path)
        }
    }

    impl Drop for TestDirectory {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn parses_details_with_section_awareness() {
        let content = r#"
[Peer]
Address = peer-address-must-not-win
PublicKey = first-server-key
Endpoint = 108.171.121.213:58493
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25

[Interface]
PublicKey = interface-public-key-must-not-win
PrivateKey = secret
Address = 10.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = second-server-key
Endpoint = second.example:51820
"#;

        let details = ConfigDetails::from_wireguard_config(content);
        assert_eq!(details.interface_address.as_deref(), Some("10.0.0.2/24"));
        assert_eq!(details.dns.as_deref(), Some("8.8.8.8"));
        assert!(details.private_key_configured);
        assert_eq!(details.peer_public_key.as_deref(), Some("first-server-key"));
        assert_eq!(details.endpoint.as_deref(), Some("108.171.121.213:58493"));
        assert_eq!(details.allowed_ips.as_deref(), Some("0.0.0.0/0"));
        assert_eq!(details.persistent_keepalive.as_deref(), Some("25"));
    }

    #[test]
    fn details_do_not_mix_fields_from_multiple_peers() {
        let content = r#"
[Interface]
PrivateKey = secret

[Peer]
PublicKey = first-peer

[Peer]
PublicKey = second-peer
Endpoint = second.example:51820
AllowedIPs = 10.0.0.0/8
"#;

        let details = ConfigDetails::from_wireguard_config(content);
        assert_eq!(details.peer_public_key.as_deref(), Some("first-peer"));
        assert_eq!(details.endpoint, None);
        assert_eq!(details.allowed_ips, None);
    }

    #[test]
    fn inspection_redacts_all_private_key_spellings() {
        let content = "[Interface]\n PrivateKey = top-secret\n[Peer]\nPRESHAREDKEY=shared-secret\nPublicKey = public\n";
        let redacted = redact_wireguard_secrets(content);
        assert!(!redacted.contains("top-secret"));
        assert!(!redacted.contains("shared-secret"));
        assert!(redacted.contains(" PrivateKey = [redacted]"));
        assert!(validate_wireguard_client_config(&redacted).is_ok());
    }

    #[test]
    fn rejects_every_wg_quick_command_hook() {
        for hook in ["PreUp", "PostUp", "PreDown", "PostDown"] {
            let content = format!(
                "[Interface]\nPrivateKey = secret\n{hook} = id\n[Peer]\nPublicKey = peer-key\n"
            );
            let error = validate_wireguard_client_config(&content).unwrap_err();
            assert!(
                error.to_string().contains("hook"),
                "unexpected error: {error}"
            );
        }
    }

    #[test]
    fn validates_interface_names() {
        for valid in ["wg0", "str-dub303", "a_b=c+d.e"] {
            validate_interface_name(valid).unwrap();
        }
        for invalid in [
            "",
            ".",
            "..",
            "all",
            "interfaces",
            "-option",
            "sixteen-char-name",
            "../escape",
            "wg 0",
            "wg\u{1b}0",
            "中文",
        ] {
            assert!(
                validate_interface_name(invalid).is_err(),
                "{invalid:?} should be invalid"
            );
        }
    }

    #[test]
    fn legacy_credential_fields_are_ignored() {
        let config: AppConfig = toml::from_str("username = 'alice'").unwrap();
        assert_eq!(config, AppConfig::default());
    }

    #[test]
    fn existing_credential_config_is_erased_and_made_private() {
        let root = TestDirectory::new("existing-config");
        let config_dir = root.0.join("app-config");
        fs::create_dir(&config_dir).unwrap();
        let config_path = config_dir.join("config.toml");
        fs::write(&config_path, "username = 'alice'").unwrap();

        #[cfg(unix)]
        fs::set_permissions(&config_path, fs::Permissions::from_mode(0o644)).unwrap();

        let manager = ConfigManager::with_directories(&config_dir, root.0.join("wg")).unwrap();
        let config = manager.load_config().unwrap();
        assert_eq!(config, AppConfig::default());
        let migrated = fs::read_to_string(&config_path).unwrap();
        assert_eq!(migrated, CONFIG_TEMPLATE);
        assert!(!migrated.contains("alice"));

        #[cfg(unix)]
        assert_eq!(
            fs::metadata(config_path).unwrap().permissions().mode() & 0o777,
            0o600
        );
    }

    #[test]
    fn parse_errors_never_echo_the_source_line() {
        let root = TestDirectory::new("redacted-parse-error");
        let config_dir = root.0.join("app-config");
        fs::create_dir(&config_dir).unwrap();
        fs::write(
            config_dir.join("config.toml"),
            "legacy_password = \"must-not-appear",
        )
        .unwrap();

        let manager = ConfigManager::with_directories(&config_dir, root.0.join("wg")).unwrap();
        let error = manager.load_config().unwrap_err().to_string();
        assert!(error.contains("Failed to parse application config"));
        assert!(!error.contains("must-not-appear"));
        assert!(!error.contains("legacy_password"));
    }

    #[test]
    fn creates_private_empty_credential_template() {
        let root = TestDirectory::new("permissions");
        let config_dir = root.0.join("app-config");
        let wg_dir = root.0.join("wireguard");
        let manager = ConfigManager::with_directories(&config_dir, &wg_dir).unwrap();
        let config = manager.load_config().unwrap();

        assert_eq!(config, AppConfig::default());
        let template = fs::read_to_string(config_dir.join("config.toml")).unwrap();
        assert!(!template.to_ascii_lowercase().contains("password"));

        #[cfg(unix)]
        {
            let directory_mode = fs::metadata(&config_dir).unwrap().permissions().mode() & 0o777;
            let file_mode = fs::metadata(config_dir.join("config.toml"))
                .unwrap()
                .permissions()
                .mode()
                & 0o777;
            assert_eq!(directory_mode, 0o700);
            assert_eq!(file_mode, 0o600);
        }
    }

    #[cfg(unix)]
    #[test]
    fn refuses_a_symlinked_application_config() {
        use std::os::unix::fs::symlink;

        let root = TestDirectory::new("symlink");
        let config_dir = root.0.join("app-config");
        fs::create_dir(&config_dir).unwrap();
        let destination = root.0.join("destination");
        fs::write(&destination, "username = 'do-not-touch'").unwrap();
        symlink(&destination, config_dir.join("config.toml")).unwrap();

        let error = ConfigManager::with_directories(&config_dir, root.0.join("wg")).unwrap_err();
        assert!(error.to_string().contains("not a regular file"));
        assert_eq!(
            fs::read_to_string(destination).unwrap(),
            "username = 'do-not-touch'"
        );
    }
}
