use anyhow::Result;
use directories::ProjectDirs;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ConfigDetails {
    pub interface_address: Option<String>,
    pub dns: Option<String>,
    pub peer_public_key: Option<String>,
    pub endpoint: Option<String>,
    pub allowed_ips: Option<String>,
    pub persistent_keepalive: Option<String>,
    pub private_key_configured: bool,
}

impl ConfigDetails {
    pub fn from_wireguard_config(content: &str) -> Self {
        let mut details = Self::default();

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let Some((key, value)) = line.split_once('=') else {
                continue;
            };

            let value = value.trim();
            match key.trim().to_ascii_lowercase().as_str() {
                "address" => details.interface_address = Some(value.to_string()),
                "dns" => details.dns = Some(value.to_string()),
                "privatekey" => details.private_key_configured = !value.is_empty(),
                "publickey" => details.peer_public_key = Some(value.to_string()),
                "endpoint" => details.endpoint = Some(value.to_string()),
                "allowedips" => details.allowed_ips = Some(value.to_string()),
                "persistentkeepalive" => details.persistent_keepalive = Some(value.to_string()),
                _ => {}
            }
        }

        details
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppConfig {
    pub username: String,
    pub password: String,
    pub auto_download: bool,
    pub last_server: Option<String>,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            username: String::new(),
            password: String::new(),
            auto_download: true,
            last_server: None,
        }
    }
}

pub struct ConfigManager {
    config_path: PathBuf,
    wg_config_dir: PathBuf,
}

impl ConfigManager {
    pub fn new() -> Result<Self> {
        let proj_dirs = ProjectDirs::from("org", "wireguard", "wireguard-tui")
            .ok_or_else(|| anyhow::anyhow!("Failed to get project directories"))?;

        let config_dir = proj_dirs.config_dir();
        let config_path = config_dir.join("config.toml");
        let wg_config_dir = PathBuf::from("/etc/wireguard");

        fs::create_dir_all(config_dir)?;

        let manager = Self {
            config_path,
            wg_config_dir,
        };

        // Auto-generate config template if not exists
        manager.ensure_config_exists()?;

        Ok(manager)
    }

    fn ensure_config_exists(&self) -> Result<()> {
        if !self.config_path.exists() {
            self.create_config_template()?;
        }
        Ok(())
    }

    fn create_config_template(&self) -> Result<()> {
        let template = r#"# WireGuard TUI Configuration File
#
# This file is automatically generated on first run.
# Please update with your StrongVPN credentials.
#
# Get your credentials from:
# 1. Login to https://strongtech.org/account/
# 2. Click "Account Setup Instructions"
# 3. Look for "VPN Account Information"
# 4. Username starts with 'a'
#
# Note: These are your VPN credentials (AIO Username/Password),
# NOT your website login email/password!

# Your StrongVPN username (starts with 'a')
username = "a314393"

# Your StrongVPN password
password = "L7W8cXG3MH"

# Automatically download configs on first run
auto_download = true

# Last connected server (managed automatically)
# last_server = "server-name"
"#;

        fs::write(&self.config_path, template)?;
        Ok(())
    }

    pub fn load_config(&self) -> Result<AppConfig> {
        if !self.config_path.exists() {
            self.create_config_template()?;
        }

        let content = fs::read_to_string(&self.config_path)?;
        let config = toml::from_str(&content)?;
        Ok(config)
    }

    pub fn get_config_path_str(&self) -> String {
        self.config_path.display().to_string()
    }

    pub fn get_wg_config_dir(&self) -> &Path {
        &self.wg_config_dir
    }

    pub fn list_configs(&self) -> Result<Vec<String>> {
        let mut configs = Vec::new();

        // 检查目录是否存在且可读
        if !self.wg_config_dir.exists() {
            return Ok(configs);
        }

        // 尝试读取目录，如果权限不足则返回空列表而不是错误
        match fs::read_dir(&self.wg_config_dir) {
            Ok(entries) => {
                for entry in entries {
                    if let Ok(entry) = entry {
                        let path = entry.path();
                        if path.extension().map_or(false, |ext| ext == "conf") {
                            if let Some(name) = path.file_stem() {
                                if let Some(name_str) = name.to_str() {
                                    configs.push(name_str.to_string());
                                }
                            }
                        }
                    }
                }
            }
            Err(_) => {
                // 权限不足，返回空列表
            }
        }

        configs.sort();
        Ok(configs)
    }

    pub fn get_config_path(&self, name: &str) -> PathBuf {
        self.wg_config_dir.join(format!("{}.conf", name))
    }

    pub fn load_config_details(&self, name: &str) -> Result<ConfigDetails> {
        let content = fs::read_to_string(self.get_config_path(name))?;
        Ok(ConfigDetails::from_wireguard_config(&content))
    }
}

#[cfg(test)]
mod tests {
    use super::ConfigDetails;

    #[test]
    fn parses_wireguard_config_details() {
        let content = r#"
[Interface]
PrivateKey = secret
Address = 10.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = server-key
Endpoint = 108.171.121.213:58493
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
"#;

        let details = ConfigDetails::from_wireguard_config(content);

        assert_eq!(details.interface_address.as_deref(), Some("10.0.0.2/24"));
        assert_eq!(details.dns.as_deref(), Some("8.8.8.8"));
        assert!(details.private_key_configured);
        assert_eq!(details.peer_public_key.as_deref(), Some("server-key"));
        assert_eq!(details.endpoint.as_deref(), Some("108.171.121.213:58493"));
        assert_eq!(details.allowed_ips.as_deref(), Some("0.0.0.0/0"));
        assert_eq!(details.persistent_keepalive.as_deref(), Some("25"));
    }
}
